-- Índice da Etapa 2 do chat semântico (ADR 001, revisado pelo ADR 003).
--
-- Este arquivo é a definição canônica do banco. Aplicá-lo num Postgres vazio,
-- rodar `npm run indice:derivar` e depois `npm run indice:carregar` (ou
-- `:carregar:https`) reconstrói o índice inteiro do zero. É o que sustenta a
-- decisão D1: o Postgres é índice, nunca fonte, e os `.json.gz` na raiz do
-- repositório continuam canônicos.
--
-- Não há migração incremental aqui de propósito. Divergência silenciosa entre a
-- base e o índice é o modo de falha que o ADR quer evitar, e reconstruir é
-- barato: minutos.

create extension if not exists pg_trgm;
create extension if not exists unaccent;

-- `unaccent(text)` é volátil porque depende do dicionário carregado, e por isso
-- não pode entrar em índice. Fixar o dicionário na chamada torna a função
-- imutável e indexável — é a forma canônica de resolver isso no Postgres, e sem
-- ela a semente do tesauro varre o acervo inteiro a cada pergunta.
create or replace function sem_acento(texto text) returns text
language sql immutable parallel safe strict as $$
  select public.unaccent('public.unaccent'::regdictionary, lower(texto))
$$;

-- ---------------------------------------------------------------- tabelas
--
-- D3: a unidade é a obra deduplicada. `documento` é a obra; `registro` é cada
-- catalogação dela. Ano, nível e macrotema vivem no registro porque é assim que
-- os gabaritos contam — o mesmo trabalho aparece em coleções diferentes, e às
-- vezes em anos de catalogação diferentes.

create table indice_meta (
  id boolean primary key default true check (id),
  base_version text not null,
  sha256_pos text not null,
  sha256_tcc text not null,
  gerado_em timestamptz not null default now(),
  registros int not null,
  documentos int not null
);

create table documento (
  id text primary key,                     -- identidade normalizada do título
  titulo text not null,
  resumo text,                             -- o mais longo entre os registros da obra
  resumo_sha256 text,
  resumo_utilizavel boolean not null default false,
  id_obra text,                            -- referência à triagem assinada; não é chave
  tsv tsvector generated always as (
    setweight(to_tsvector('portuguese', coalesce(titulo, '')), 'A') ||
    setweight(to_tsvector('portuguese', coalesce(resumo, '')), 'B')
  ) stored
);

create table registro (
  id bigint generated by default as identity primary key,
  documento_id text not null references documento(id) on delete cascade,
  colecao text not null,
  catalogo text not null check (catalogo in ('ppg', 'tcc')),
  ano int,
  nivel_academico text,
  macrotema text,
  url text,
  -- Cobertura do próprio registro. Diferente da cobertura da obra: entre
  -- registros da mesma obra fica o resumo mais longo, e confundir as duas erra
  -- o gabarito de Q04 sem parecer erro.
  resumo_utilizavel boolean not null default false
);

-- D11 ainda não vale aqui: na Etapa 2 uma pessoa é uma grafia. A unificação
-- canônica da Etapa 5 funde linhas de `pessoa` sem reescrever `registro_pessoa`.
create table pessoa (
  id bigint generated by default as identity primary key,
  nome_canonico text not null unique
);

create table pessoa_grafia (
  grafia text primary key,
  pessoa_id bigint not null references pessoa(id) on delete cascade
);

create table registro_pessoa (
  registro_id bigint not null references registro(id) on delete cascade,
  pessoa_id bigint not null references pessoa(id) on delete cascade,
  papel text not null check (papel in ('Autor', 'Orientador', 'Co-orientador')),
  primary key (registro_id, pessoa_id, papel)
);

create table registro_palavra_chave (
  registro_id bigint not null references registro(id) on delete cascade,
  termo text not null,
  primary key (registro_id, termo)
);

-- ---------------------------------------------------------------- índices
--
-- D2: o FTS do Postgres com dicionário português resolve nome próprio e termo
-- exato. O título pesa mais que o resumo: quem procura "empreendedorismo
-- feminino" quer primeiro o trabalho que se chama assim.
create index documento_tsv_idx on documento using gin (tsv);
create index documento_titulo_trgm_idx on documento using gin (titulo gin_trgm_ops);
create index documento_resumo_trgm_idx on documento using gin (resumo gin_trgm_ops);
create index documento_id_obra_idx on documento (id_obra);
create index registro_documento_idx on registro (documento_id);
create index registro_colecao_idx on registro (colecao);
create index registro_ano_idx on registro (ano);
create index registro_macrotema_idx on registro (macrotema);
create index registro_nivel_idx on registro (nivel_academico);
create index registro_cobertura_idx on registro (resumo_utilizavel);
create index registro_pessoa_pessoa_idx on registro_pessoa (pessoa_id, papel);
create index registro_palavra_chave_termo_idx on registro_palavra_chave (termo);

-- Sem estes três, a semente do tesauro é uma varredura sequencial de 85 mil
-- documentos contra um hash de 356 mil linhas: quatro segundos por pergunta,
-- acima do teto do papel anônimo. Com eles, 81 milissegundos.
create index documento_titulo_norm_idx on documento using gin (sem_acento(titulo) gin_trgm_ops);
create index palavra_chave_norm_idx on registro_palavra_chave using gin (sem_acento(termo) gin_trgm_ops);
create index registro_macrotema_norm_idx on registro using gin (sem_acento(macrotema) gin_trgm_ops);

-- Quantos documentos contêm cada lexema é propriedade do índice, não da
-- pergunta. Calcular a cada consulta custava segundos — lexema comum como
-- "trabalh" casa 45 mil documentos. Aqui é uma vez por carga, e o tesauro vira
-- uma junção.
create table lexema_frequencia (
  lexema text primary key,
  documentos int not null
);

-- ------------------------------------------------------------------- RLS
--
-- A chave anônima é pública num app estático: leitura para todos, escrita para
-- ninguém. Não existe política de insert, update ou delete, e não existe função
-- que altere dado — a carga entra pela chave de serviço, fora do app.
alter table indice_meta enable row level security;
alter table documento enable row level security;
alter table registro enable row level security;
alter table pessoa enable row level security;
alter table pessoa_grafia enable row level security;
alter table registro_pessoa enable row level security;
alter table registro_palavra_chave enable row level security;
alter table lexema_frequencia enable row level security;

create policy leitura_publica on indice_meta for select to anon, authenticated using (true);
create policy leitura_publica on documento for select to anon, authenticated using (true);
create policy leitura_publica on registro for select to anon, authenticated using (true);
create policy leitura_publica on pessoa for select to anon, authenticated using (true);
create policy leitura_publica on pessoa_grafia for select to anon, authenticated using (true);
create policy leitura_publica on registro_pessoa for select to anon, authenticated using (true);
create policy leitura_publica on registro_palavra_chave for select to anon, authenticated using (true);
create policy leitura_publica on lexema_frequencia for select to anon, authenticated using (true);

-- ------------------------------------------------- tesauro e busca por texto
--
-- A hipótese testada na Etapa 2: a lacuna temática é de vocabulário, não de
-- semântica. Quem pergunta "empreendedorismo feminino" não alcança o trabalho
-- que escreveu "mulheres à frente de pequenas empresas" — mas as obras que a
-- busca literal já acha têm, nos próprios resumos, as palavras que as outras
-- usam.
--
-- Funciona, com um limite estrutural registrado no ADR 003: o tesauro é
-- iniciado pelo próprio casamento léxico que deveria substituir. Semente
-- grande, expansão boa; semente de três obras, expansão ruim.

create or replace function tesauro(consulta text, termos int default 8)
returns table (lexema text, na_semente bigint, no_acervo bigint, lift numeric)
language sql stable parallel safe as $$
  -- Cada filtro roda na sua própria tabela, usando o próprio índice, e o
  -- conjunto de ids — pequeno por definição — volta para `documento`. Montar a
  -- semente ao contrário, varrendo os documentos e filtrando depois, custava
  -- 50 vezes mais.
  with semente as (
    select d.id, d.tsv from documento d
    where sem_acento(d.titulo) like '%' || sem_acento(consulta) || '%'
    union
    select d.id, d.tsv from documento d
    where d.id in (
      select r.documento_id from registro r
      where sem_acento(r.macrotema) like '%' || sem_acento(consulta) || '%'
      union
      select r.documento_id from registro r
      join registro_palavra_chave pc on pc.registro_id = r.id
      where sem_acento(pc.termo) like '%' || sem_acento(consulta) || '%'
    )
  ),
  total as (select count(*)::numeric as n from semente),
  candidatos as (
    select lex::text as lexema, count(distinct s.id) as na_semente
    from semente s, unnest(tsvector_to_array(s.tsv)) lex
    where length(lex) >= 4
    group by lex
    having count(distinct s.id) >= greatest(2, ceil((select n from total) / 3))
  )
  select c.lexema, c.na_semente, f.documentos::bigint,
    round((c.na_semente / (select n from total)) / nullif(f.documentos::numeric / 85567, 0), 1)
  from candidatos c join lexema_frequencia f on f.lexema = c.lexema
  order by 4 desc nulls last
  limit termos;
$$;

-- `lexema_frequencia` envelhece junto com `documento`: recalcular é parte da
-- carga, não manutenção à parte. `security definer` porque quem carrega chama
-- pela API com a chave de serviço, e a função escreve numa tabela sob RLS.
create or replace function atualizar_lexema_frequencia()
returns bigint
language plpgsql security definer
set search_path = public
as $$
declare n bigint;
begin
  delete from lexema_frequencia;
  insert into lexema_frequencia (lexema, documentos)
  select word, ndoc from ts_stat('select tsv from documento') where ndoc >= 2;
  get diagnostics n = row_count;
  analyze lexema_frequencia;
  return n;
end;
$$;

revoke execute on function atualizar_lexema_frequencia() from public, anon, authenticated;
grant execute on function atualizar_lexema_frequencia() to service_role;

-- O lexema de maior `lift` é obrigatório: é o núcleo do tema, e sem ele o
-- resultado vira outra coisa. Entram como alternativa os que aparecem em metade
-- ou mais da semente — é o que separa vocabulário do tema ("mulher") de
-- vocabulário de método ("exploratório"), presente em poucas obras e por acaso
-- raro no acervo. Sem semente não há o que expandir, e cai na consulta literal:
-- não inventar vocabulário que o acervo não sustenta é a regra R4 do ADR 003.
create or replace function consulta_expandida(consulta text)
returns tsquery
language sql stable as $$
  with t as (select * from tesauro(consulta, 8)),
  semente as (select max(na_semente) as n from t),
  nucleo as (select lexema from t order by lift desc limit 1),
  alternativas as (
    select lexema from t
    where lexema <> (select lexema from nucleo)
      and na_semente >= ceil((select n from semente) / 2.0)
  )
  select case
    when not exists (select 1 from nucleo) then websearch_to_tsquery('portuguese', consulta)
    when not exists (select 1 from alternativas)
      then to_tsquery('simple', quote_literal((select lexema from nucleo)))
    else to_tsquery('simple', quote_literal((select lexema from nucleo))) && (
      select to_tsquery('simple', string_agg(quote_literal(lexema), ' | ')) from alternativas
    )
  end;
$$;

-- O limite padrão é a profundidade da decisão D8 (15 a 25 resumos por
-- pergunta), e é onde a medição encontrou o melhor par: 79% de revocação com
-- 76% de precisão em Q10.
create or replace function buscar_texto(consulta text, limite int default 25)
returns table (documento_id text, titulo text, aderencia real)
language sql stable as $$
  select d.id, d.titulo, ts_rank(d.tsv, q) as aderencia
  from documento d, consulta_expandida(consulta) q
  where d.tsv @@ q
  order by ts_rank(d.tsv, q) desc, d.titulo
  limit limite;
$$;

-- --------------------------------------------------- consulta estruturada
--
-- D2: o que é contagem sai daqui, em SQL, e nunca da recuperação por
-- similaridade. "Quantos" respondido por aproximação produz número errado com
-- aparência de certeza. Cada função devolve também a unidade do que contou:
-- registro e trabalho distinto são números diferentes, e a resposta que não diz
-- qual está usando reprova pelo gabarito da Etapa 0.

create or replace function contar_acervo()
returns table (registros bigint, trabalhos_distintos bigint, com_resumo bigint, sem_resumo bigint,
               colecoes bigint, base_version text, unidade text)
language sql stable as $$
  select (select count(*) from registro),
         (select count(*) from documento),
         (select count(*) from registro where resumo_utilizavel),
         (select count(*) from registro where not resumo_utilizavel),
         (select count(distinct colecao) from registro),
         (select base_version from indice_meta),
         'registros do acervo; trabalhos distintos deduplicam a mesma obra catalogada em mais de uma coleção';
$$;

create or replace function serie_anual(colecao_filtro text default null)
returns table (ano int, registros bigint, em_coleta boolean)
language sql stable as $$
  with s as (
    select r.ano, count(*) as n from registro r
    where r.ano is not null
      and (colecao_filtro is null or unaccent(lower(r.colecao)) like '%' || unaccent(lower(colecao_filtro)) || '%')
    group by r.ano
  )
  -- O último ano da série está em coleta: dá-lo como produção fechada reprova
  -- por Q23, e quem responde precisa saber disso sem ter que inferir.
  select s.ano::int, s.n, s.ano = (select max(ano) from s) from s order by s.ano;
$$;

create or replace function recorte_da_colecao(nome text)
returns table (colecao text, registros bigint, trabalhos_distintos bigint, sem_resumo bigint,
               ano_min int, ano_max int, niveis text)
language sql stable as $$
  select r.colecao, count(*), count(distinct r.documento_id),
         count(*) filter (where not r.resumo_utilizavel),
         min(r.ano)::int, max(r.ano)::int,
         string_agg(distinct r.nivel_academico, '; ')
  from registro r
  where unaccent(lower(r.colecao)) like '%' || unaccent(lower(nome)) || '%'
  group by r.colecao order by count(*) desc;
$$;

create or replace function pessoa_no_indice(nome text)
returns table (grafia text, papel text, registros bigint, trabalhos_distintos bigint, colecoes bigint, unidade text)
language sql stable as $$
  select p.nome_canonico, rp.papel, count(*), count(distinct r.documento_id), count(distinct r.colecao),
         'conta grafias, não pessoas unificadas: a unificação canônica é a Etapa 5'
  from pessoa p
  join registro_pessoa rp on rp.pessoa_id = p.id
  join registro r on r.id = rp.registro_id
  where unaccent(lower(p.nome_canonico)) like '%' || unaccent(lower(nome)) || '%'
  group by p.nome_canonico, rp.papel
  order by count(*) desc;
$$;

create or replace function top_macrotemas(limite int default 10)
returns table (macrotema text, registros bigint, origem text)
language sql stable as $$
  select r.macrotema, count(*), 'classificação automática da base, não categoria oficial do programa'
  from registro r where r.macrotema is not null
  group by r.macrotema order by count(*) desc limit limite;
$$;

create or replace function registros_do_titulo(titulo_busca text)
returns table (documento_id text, titulo text, colecao text, ano int, url text)
language sql stable as $$
  select d.id, d.titulo, r.colecao, r.ano::int, r.url
  from documento d join registro r on r.documento_id = d.id
  where d.id = unaccent(lower(regexp_replace(trim(titulo_busca), '\s+', ' ', 'g')))
     or unaccent(lower(d.titulo)) like '%' || unaccent(lower(titulo_busca)) || '%'
  order by r.ano nulls last;
$$;

grant execute on function contar_acervo, serie_anual(text), recorte_da_colecao(text),
  pessoa_no_indice(text), top_macrotemas(int), registros_do_titulo(text),
  buscar_texto(text, int), consulta_expandida(text), tesauro(text, int) to anon, authenticated;
