-- Índice da Etapa 2 do chat semântico (ADR 001, revisado pelo ADR 003).
--
-- Este arquivo é a definição canônica do banco. Aplicá-lo num Postgres vazio,
-- rodar `npm run indice:derivar` e depois `npm run indice:carregar` (ou
-- `:carregar:https`) reconstrói o índice inteiro do zero. É o que sustenta a
-- decisão D1: o Postgres é índice, nunca fonte, e os `.json.gz` na raiz do
-- repositório continuam canônicos.
--
-- Não há migração incremental aqui de propósito. Divergência silenciosa entre a
-- base e o índice é o modo de falha que o ADR quer evitar, e reconstruir é
-- barato: minutos.

create extension if not exists pg_trgm;
create extension if not exists unaccent;

-- `unaccent(text)` é volátil porque depende do dicionário carregado, e por isso
-- não pode entrar em índice. Fixar o dicionário na chamada torna a função
-- imutável e indexável — é a forma canônica de resolver isso no Postgres, e sem
-- ela a semente do tesauro varre o acervo inteiro a cada pergunta.
create or replace function sem_acento(texto text) returns text
language sql immutable parallel safe strict as $$
  select public.unaccent('public.unaccent'::regdictionary, lower(texto))
$$;

-- ---------------------------------------------------------------- tabelas
--
-- D3: a unidade é a obra deduplicada. `documento` é a obra; `registro` é cada
-- catalogação dela. Ano, nível e macrotema vivem no registro porque é assim que
-- os gabaritos contam — o mesmo trabalho aparece em coleções diferentes, e às
-- vezes em anos de catalogação diferentes.

create table indice_meta (
  id boolean primary key default true check (id),
  base_version text not null,
  sha256_pos text not null,
  sha256_tcc text not null,
  gerado_em timestamptz not null default now(),
  registros int not null,
  documentos int not null
);

create table documento (
  id text primary key,                     -- identidade normalizada do título
  titulo text not null,
  resumo text,                             -- o mais longo entre os registros da obra
  resumo_sha256 text,
  resumo_utilizavel boolean not null default false,
  id_obra text,                            -- referência à triagem assinada; não é chave
  tsv tsvector generated always as (
    setweight(to_tsvector('portuguese', coalesce(titulo, '')), 'A') ||
    setweight(to_tsvector('portuguese', coalesce(resumo, '')), 'B')
  ) stored
);

create table registro (
  id bigint generated by default as identity primary key,
  documento_id text not null references documento(id) on delete cascade,
  colecao text not null,
  catalogo text not null check (catalogo in ('ppg', 'tcc')),
  ano int,
  nivel_academico text,
  macrotema text,
  url text,
  -- Cobertura do próprio registro. Diferente da cobertura da obra: entre
  -- registros da mesma obra fica o resumo mais longo, e confundir as duas erra
  -- o gabarito de Q04 sem parecer erro.
  resumo_utilizavel boolean not null default false
);

-- D11 ainda não vale aqui: na Etapa 2 uma pessoa é uma grafia. A unificação
-- canônica da Etapa 5 funde linhas de `pessoa` sem reescrever `registro_pessoa`.
create table pessoa (
  id bigint generated by default as identity primary key,
  nome_canonico text not null unique
);

create table pessoa_grafia (
  grafia text primary key,
  pessoa_id bigint not null references pessoa(id) on delete cascade
);

create table registro_pessoa (
  registro_id bigint not null references registro(id) on delete cascade,
  pessoa_id bigint not null references pessoa(id) on delete cascade,
  papel text not null check (papel in ('Autor', 'Orientador', 'Co-orientador')),
  primary key (registro_id, pessoa_id, papel)
);

create table registro_palavra_chave (
  registro_id bigint not null references registro(id) on delete cascade,
  termo text not null,
  primary key (registro_id, termo)
);

-- ---------------------------------------------------------------- índices
--
-- D2: o FTS do Postgres com dicionário português resolve nome próprio e termo
-- exato. O título pesa mais que o resumo: quem procura "empreendedorismo
-- feminino" quer primeiro o trabalho que se chama assim.
create index documento_tsv_idx on documento using gin (tsv);
create index documento_titulo_trgm_idx on documento using gin (titulo gin_trgm_ops);
create index documento_resumo_trgm_idx on documento using gin (resumo gin_trgm_ops);
create index documento_id_obra_idx on documento (id_obra);
create index registro_documento_idx on registro (documento_id);
create index registro_colecao_idx on registro (colecao);
create index registro_ano_idx on registro (ano);
create index registro_macrotema_idx on registro (macrotema);
create index registro_nivel_idx on registro (nivel_academico);
create index registro_cobertura_idx on registro (resumo_utilizavel);
create index registro_pessoa_pessoa_idx on registro_pessoa (pessoa_id, papel);
create index registro_palavra_chave_termo_idx on registro_palavra_chave (termo);

-- Sem estes três, a semente do tesauro é uma varredura sequencial de 85 mil
-- documentos contra um hash de 356 mil linhas: quatro segundos por pergunta,
-- acima do teto do papel anônimo. Com eles, 81 milissegundos.
create index documento_titulo_norm_idx on documento using gin (sem_acento(titulo) gin_trgm_ops);
create index palavra_chave_norm_idx on registro_palavra_chave using gin (sem_acento(termo) gin_trgm_ops);
create index registro_macrotema_norm_idx on registro using gin (sem_acento(macrotema) gin_trgm_ops);

-- Quantos documentos contêm cada lexema é propriedade do índice, não da
-- pergunta. Calcular a cada consulta custava segundos — lexema comum como
-- "trabalh" casa 45 mil documentos. Aqui é uma vez por carga, e o tesauro vira
-- uma junção.
create table lexema_frequencia (
  lexema text primary key,
  documentos int not null
);

-- ------------------------------------------------------------------- RLS
--
-- A chave anônima é pública num app estático: leitura para todos, escrita para
-- ninguém. Não existe política de insert, update ou delete, e não existe função
-- que altere dado — a carga entra pela chave de serviço, fora do app.
alter table indice_meta enable row level security;
alter table documento enable row level security;
alter table registro enable row level security;
alter table pessoa enable row level security;
alter table pessoa_grafia enable row level security;
alter table registro_pessoa enable row level security;
alter table registro_palavra_chave enable row level security;
alter table lexema_frequencia enable row level security;

create policy leitura_publica on indice_meta for select to anon, authenticated using (true);
create policy leitura_publica on documento for select to anon, authenticated using (true);
create policy leitura_publica on registro for select to anon, authenticated using (true);
create policy leitura_publica on pessoa for select to anon, authenticated using (true);
create policy leitura_publica on pessoa_grafia for select to anon, authenticated using (true);
create policy leitura_publica on registro_pessoa for select to anon, authenticated using (true);
create policy leitura_publica on registro_palavra_chave for select to anon, authenticated using (true);
create policy leitura_publica on lexema_frequencia for select to anon, authenticated using (true);

-- ------------------------------------------------- tesauro e busca por texto
--
-- A hipótese testada na Etapa 2: a lacuna temática é de vocabulário, não de
-- semântica. Quem pergunta "empreendedorismo feminino" não alcança o trabalho
-- que escreveu "mulheres à frente de pequenas empresas" — mas as obras que a
-- busca literal já acha têm, nos próprios resumos, as palavras que as outras
-- usam.
--
-- Funciona, com um limite estrutural registrado no ADR 003: o tesauro é
-- iniciado pelo próprio casamento léxico que deveria substituir. Semente
-- grande, expansão boa; semente de três obras, expansão ruim.

create or replace function tesauro(consulta text, termos int default 8)
returns table (lexema text, na_semente bigint, no_acervo bigint, lift numeric)
language sql stable parallel safe as $$
  -- Cada filtro roda na sua própria tabela, usando o próprio índice, e o
  -- conjunto de ids — pequeno por definição — volta para `documento`. Montar a
  -- semente ao contrário, varrendo os documentos e filtrando depois, custava
  -- 50 vezes mais.
  with semente as (
    select d.id, d.tsv from documento d
    where sem_acento(d.titulo) like '%' || sem_acento(consulta) || '%'
    union
    select d.id, d.tsv from documento d
    where d.id in (
      select r.documento_id from registro r
      where sem_acento(r.macrotema) like '%' || sem_acento(consulta) || '%'
      union
      select r.documento_id from registro r
      join registro_palavra_chave pc on pc.registro_id = r.id
      where sem_acento(pc.termo) like '%' || sem_acento(consulta) || '%'
    )
  ),
  total as (select count(*)::numeric as n from semente),
  candidatos as (
    select lex::text as lexema, count(distinct s.id) as na_semente
    from semente s, unnest(tsvector_to_array(s.tsv)) lex
    where length(lex) >= 4
    group by lex
    having count(distinct s.id) >= greatest(2, ceil((select n from total) / 3))
  )
  select c.lexema, c.na_semente, f.documentos::bigint,
    round((c.na_semente / (select n from total)) / nullif(f.documentos::numeric / 85567, 0), 1)
  from candidatos c join lexema_frequencia f on f.lexema = c.lexema
  order by 4 desc nulls last
  limit termos;
$$;

-- `lexema_frequencia` envelhece junto com `documento`: recalcular é parte da
-- carga, não manutenção à parte. `security definer` porque quem carrega chama
-- pela API com a chave de serviço, e a função escreve numa tabela sob RLS.
create or replace function atualizar_lexema_frequencia()
returns bigint
language plpgsql security definer
set search_path = public
as $$
declare n bigint;
begin
  delete from lexema_frequencia;
  insert into lexema_frequencia (lexema, documentos)
  select word, ndoc from ts_stat('select tsv from documento') where ndoc >= 2;
  get diagnostics n = row_count;
  analyze lexema_frequencia;
  return n;
end;
$$;

revoke execute on function atualizar_lexema_frequencia() from public, anon, authenticated;
grant execute on function atualizar_lexema_frequencia() to service_role;

-- O lexema de maior `lift` é obrigatório: é o núcleo do tema, e sem ele o
-- resultado vira outra coisa. Entram como alternativa os que aparecem em metade
-- ou mais da semente — é o que separa vocabulário do tema ("mulher") de
-- vocabulário de método ("exploratório"), presente em poucas obras e por acaso
-- raro no acervo. Sem semente não há o que expandir, e cai na consulta literal:
-- não inventar vocabulário que o acervo não sustenta é a regra R4 do ADR 003.
create or replace function consulta_expandida(consulta text)
returns tsquery
language sql stable as $$
  with t as (select * from tesauro(consulta, 8)),
  semente as (select max(na_semente) as n from t),
  nucleo as (select lexema from t order by lift desc limit 1),
  alternativas as (
    select lexema from t
    where lexema <> (select lexema from nucleo)
      and na_semente >= ceil((select n from semente) / 2.0)
  )
  select case
    when not exists (select 1 from nucleo) then websearch_to_tsquery('portuguese', consulta)
    when not exists (select 1 from alternativas)
      then to_tsquery('simple', quote_literal((select lexema from nucleo)))
    else to_tsquery('simple', quote_literal((select lexema from nucleo))) && (
      select to_tsquery('simple', string_agg(quote_literal(lexema), ' | ')) from alternativas
    )
  end;
$$;

-- O limite padrão é a profundidade da decisão D8 (15 a 25 resumos por
-- pergunta), e é onde a medição encontrou o melhor par: 79% de revocação com
-- 76% de precisão em Q10.
create or replace function buscar_texto(consulta text, limite int default 25)
returns table (documento_id text, titulo text, aderencia real)
language sql stable as $$
  select d.id, d.titulo, ts_rank(d.tsv, q) as aderencia
  from documento d, consulta_expandida(consulta) q
  where d.tsv @@ q
  order by ts_rank(d.tsv, q) desc, d.titulo
  limit limite;
$$;

-- --------------------------------------------------- consulta estruturada
--
-- D2: o que é contagem sai daqui, em SQL, e nunca da recuperação por
-- similaridade. "Quantos" respondido por aproximação produz número errado com
-- aparência de certeza. Cada função devolve também a unidade do que contou:
-- registro e trabalho distinto são números diferentes, e a resposta que não diz
-- qual está usando reprova pelo gabarito da Etapa 0.

create or replace function contar_acervo()
returns table (registros bigint, trabalhos_distintos bigint, com_resumo bigint, sem_resumo bigint,
               colecoes bigint, base_version text, unidade text)
language sql stable as $$
  select (select count(*) from registro),
         (select count(*) from documento),
         (select count(*) from registro where resumo_utilizavel),
         (select count(*) from registro where not resumo_utilizavel),
         (select count(distinct colecao) from registro),
         (select base_version from indice_meta),
         'registros do acervo; trabalhos distintos deduplicam a mesma obra catalogada em mais de uma coleção';
$$;

create or replace function serie_anual(colecao_filtro text default null)
returns table (ano int, registros bigint, em_coleta boolean)
language sql stable as $$
  with s as (
    select r.ano, count(*) as n from registro r
    where r.ano is not null
      and (colecao_filtro is null or unaccent(lower(r.colecao)) like '%' || unaccent(lower(colecao_filtro)) || '%')
    group by r.ano
  )
  -- O último ano da série está em coleta: dá-lo como produção fechada reprova
  -- por Q23, e quem responde precisa saber disso sem ter que inferir.
  select s.ano::int, s.n, s.ano = (select max(ano) from s) from s order by s.ano;
$$;

create or replace function recorte_da_colecao(nome text)
returns table (colecao text, registros bigint, trabalhos_distintos bigint, sem_resumo bigint,
               ano_min int, ano_max int, niveis text)
language sql stable as $$
  select r.colecao, count(*), count(distinct r.documento_id),
         count(*) filter (where not r.resumo_utilizavel),
         min(r.ano)::int, max(r.ano)::int,
         string_agg(distinct r.nivel_academico, '; ')
  from registro r
  where unaccent(lower(r.colecao)) like '%' || unaccent(lower(nome)) || '%'
  group by r.colecao order by count(*) desc;
$$;

create or replace function pessoa_no_indice(nome text)
returns table (grafia text, papel text, registros bigint, trabalhos_distintos bigint, colecoes bigint, unidade text)
language sql stable as $$
  select p.nome_canonico, rp.papel, count(*), count(distinct r.documento_id), count(distinct r.colecao),
         'pessoa unificada pela unificação automática conservadora (ADR 004), ainda sem curadoria humana; a grafia exibida é a canônica'
  from pessoa p
  join registro_pessoa rp on rp.pessoa_id = p.id
  join registro r on r.id = rp.registro_id
  where unaccent(lower(p.nome_canonico)) like '%' || unaccent(lower(nome)) || '%'
  group by p.nome_canonico, rp.papel
  order by count(*) desc;
$$;

create or replace function top_macrotemas(limite int default 10)
returns table (macrotema text, registros bigint, origem text)
language sql stable as $$
  select r.macrotema, count(*), 'classificação automática da base, não categoria oficial do programa'
  from registro r where r.macrotema is not null
  group by r.macrotema order by count(*) desc limit limite;
$$;

create or replace function registros_do_titulo(titulo_busca text)
returns table (documento_id text, titulo text, colecao text, ano int, url text)
language sql stable as $$
  select d.id, d.titulo, r.colecao, r.ano::int, r.url
  from documento d join registro r on r.documento_id = d.id
  where d.id = unaccent(lower(regexp_replace(trim(titulo_busca), '\s+', ' ', 'g')))
     or unaccent(lower(d.titulo)) like '%' || unaccent(lower(titulo_busca)) || '%'
  order by r.ano nulls last;
$$;

grant execute on function contar_acervo, serie_anual(text), recorte_da_colecao(text),
  pessoa_no_indice(text), top_macrotemas(int), registros_do_titulo(text),
  buscar_texto(text, int), consulta_expandida(text), tesauro(text, int) to anon, authenticated;

-- ============================================================================
-- Fase A0 do ADR 004: o índice enriquecido com o que o EcoGrad calcula.
--
-- Duas origens, e a diferença importa:
--
-- - `pessoa_fusao` e `rede_metrica` vêm de `npm run indice:enriquecer`, que roda
--   em Node o mesmo `unificacao.ts` e `sna-engine.ts` do app. Métrica de rede
--   reescrita em SQL divergiria da tela em silêncio.
-- - As tabelas `*_perfil`, `pessoa_termo`, `pessoa_macrotema`, `pessoa_colecao`,
--   `orientacao` e `colecao_ano` são agregados do próprio índice, refeitos por
--   `atualizar_perfis()` no fim de cada carga. Não são fonte: apagar e refazer
--   dá o mesmo resultado.
--
-- Unidade em todo nome de coluna: `obras_*` conta trabalhos distintos (D3),
-- `registros_*` conta catalogações. As duas diferem sempre que a mesma obra
-- aparece em mais de uma coleção, e trocar uma pela outra é o erro que a
-- aferição reprova.
-- ============================================================================

create table pessoa_fusao (
  grafia text primary key,
  canonico text not null,
  metodo text not null check (metodo in ('normalizacao', 'abreviacao')),
  -- A curadoria humana vem depois (ADR 004): até lá, toda fusão é automática.
  revisado_em date,
  revisado_por text,
  decisao text check (decisao in ('confirmada', 'desfeita'))
);
comment on table pessoa_fusao is 'Grafias fundidas pela unificação automática conservadora. metodo=normalizacao: iguais sem acento, caixa, pontuação e partículas; metodo=abreviacao: forma curta com uma única forma longa compatível e coleção em comum.';

create table rede_metrica (
  escopo text not null check (escopo in ('acervo', 'colecao')),
  colecao text,                              -- nulo quando escopo = acervo
  tipo text not null,                        -- Autor, Orientador, Palavra-chave, Macrotema, Artefato (Ontologia IA)
  rotulo text not null,
  pessoa_id bigint references pessoa(id) on delete set null,
  grau_absoluto int,
  grau double precision,
  intermediacao double precision,
  proximidade double precision,
  agrupamento double precision,
  comunidade int,
  ranking int,
  ranking_entre_pessoas int,
  nos_na_rede int not null,
  check ((escopo = 'acervo') = (colecao is null))
);
create index rede_metrica_pessoa_idx on rede_metrica (pessoa_id, escopo);
create index rede_metrica_rotulo_idx on rede_metrica (rotulo, escopo);
create index rede_metrica_colecao_idx on rede_metrica (colecao, tipo);
comment on table rede_metrica is 'Métricas da rede documento–pessoa–palavra-chave–macrotema do EcoGrad (sna-engine.ts), calculadas sobre o acervo inteiro (escopo=acervo) e sobre cada coleção sozinha (escopo=colecao). O valor depende do escopo: a intermediação de alguém no acervo não é a mesma que dentro da sua coleção. Coorientadores não são nós desta rede. Nomes de pessoa já unificados.';
comment on column rede_metrica.grau is 'Degree centrality normalizada (0 a 1).';
comment on column rede_metrica.intermediacao is 'Betweenness centrality; aproximada por amostragem de pivôs acima de 1.500 nós, com semente fixa.';
comment on column rede_metrica.proximidade is 'Closeness centrality; aproximada por 256 pivôs acima de 4.000 nós.';
comment on column rede_metrica.agrupamento is 'Coeficiente de clustering local.';
comment on column rede_metrica.comunidade is 'Comunidade de Louvain dentro do escopo; o número só compara nós do mesmo escopo.';
comment on column rede_metrica.ranking is 'Posição por intermediação decrescente entre TODOS os nós do escopo, inclusive documentos, palavras-chave e macrotemas (1 = maior ponte). Para comparar só pessoas, ordene por intermediacao filtrando tipo.';

-- Mesma regra de `tokensDeNome` em `unificacao.ts`, para a pergunta casar com o
-- nome em qualquer ordem.
create or replace function tokens_de_nome(nome text) returns text[]
language sql immutable parallel safe
set search_path = public
as $$
  select coalesce(array_agg(distinct t order by t), '{}')
  from regexp_split_to_table(regexp_replace(sem_acento(coalesce(nome, '')), '[^a-z0-9]+', ' ', 'g'), ' ') t
  where length(t) > 1 and t not in ('de', 'da', 'do', 'das', 'dos', 'e', 'del', 'la', 'y')
$$;

create table pessoa_perfil (
  pessoa_id bigint primary key references pessoa(id) on delete cascade,
  nome text not null,
  grafias int not null,
  obras_como_autor int not null,
  obras_orientadas int not null,
  obras_coorientadas int not null,
  registros_como_autor int not null,
  registros_orientados int not null,
  registros_coorientados int not null,
  orientadas_doutorado int not null,
  orientadas_mestrado int not null,
  orientadas_tcc_graduacao int not null,
  orientadas_tcc_especializacao int not null,
  orientandos_distintos int not null,
  primeiro_ano int,
  ultimo_ano int,
  primeiro_ano_orientando int,
  ultimo_ano_orientando int,
  colecoes int not null,
  colecao_principal text,
  palavras_chave_como_autor text[] not null,
  palavras_chave_como_orientador text[] not null,
  macrotemas_como_autor text[] not null,
  macrotemas_como_orientador text[] not null,
  intermediacao_acervo double precision,
  ranking_acervo int,
  -- Tokens do nome sem acento, caixa, pontuação e partículas, em ordem alfabética:
  -- é o que deixa achar "patricia de sa freire" em "Freire, Patricia De Sa".
  nome_tokens text[] not null default '{}'
);
create index pessoa_perfil_tokens_idx on pessoa_perfil using gin (nome_tokens);
create index pessoa_perfil_nome_idx on pessoa_perfil using gin (sem_acento(nome) gin_trgm_ops);
comment on table pessoa_perfil is 'Uma linha por pessoa unificada, com contagens por papel. obras_* conta trabalhos distintos; registros_* conta catalogações. Orientação histórica não informa vínculo atual nem disponibilidade.';
comment on column pessoa_perfil.grafias is 'Quantas grafias do acervo foram unificadas nesta pessoa (1 = nenhuma fusão).';
comment on column pessoa_perfil.orientadas_tcc_graduacao is 'Obras orientadas de nível TCC (Graduação).';
comment on column pessoa_perfil.orientandos_distintos is 'Autores distintos orientados ou coorientados pela pessoa, em qualquer nível; pode passar do número de obras, porque uma obra pode ter mais de um autor.';
comment on column pessoa_perfil.primeiro_ano is 'Primeiro ano com qualquer papel.';
comment on column pessoa_perfil.primeiro_ano_orientando is 'Primeiro ano como orientador ou coorientador.';
comment on column pessoa_perfil.colecao_principal is 'Coleção com mais registros da pessoa, em qualquer papel.';
comment on column pessoa_perfil.palavras_chave_como_autor is 'Até 10 palavras-chave mais frequentes nas obras em que é autor, da mais para a menos frequente. Lista completa em pessoa_termo.';
comment on column pessoa_perfil.palavras_chave_como_orientador is 'Até 10 palavras-chave mais frequentes nas obras que orientou ou coorientou. Lista completa em pessoa_termo.';
comment on column pessoa_perfil.macrotemas_como_autor is 'Até 5 macrotemas; classificação automática da base (NMF), não categoria oficial do programa.';
comment on column pessoa_perfil.ranking_acervo is 'Posição por intermediação entre todos os nós da rede do acervo, inclusive documentos e palavras-chave; não é posição entre pessoas.';
comment on column pessoa_perfil.intermediacao_acervo is 'Betweenness na rede do acervo inteiro (rede_metrica, escopo=acervo).';

create table pessoa_termo (
  pessoa_id bigint not null references pessoa(id) on delete cascade,
  papel text not null check (papel in ('Autor', 'Orientador', 'Co-orientador')),
  termo text not null,
  obras int not null,
  primary key (pessoa_id, papel, termo)
);
create index pessoa_termo_termo_idx on pessoa_termo using gin (sem_acento(termo) gin_trgm_ops);
comment on table pessoa_termo is 'Palavras-chave das obras de cada pessoa, por papel, com quantas obras distintas usam o termo.';

create table pessoa_macrotema (
  pessoa_id bigint not null references pessoa(id) on delete cascade,
  papel text not null check (papel in ('Autor', 'Orientador', 'Co-orientador')),
  macrotema text not null,
  obras int not null,
  primary key (pessoa_id, papel, macrotema)
);
comment on table pessoa_macrotema is 'Macrotemas (classificação automática NMF da base) das obras de cada pessoa, por papel.';

create table pessoa_colecao (
  pessoa_id bigint not null references pessoa(id) on delete cascade,
  colecao text not null,
  papel text not null check (papel in ('Autor', 'Orientador', 'Co-orientador')),
  obras int not null,
  registros int not null,
  primeiro_ano int,
  ultimo_ano int,
  primary key (pessoa_id, colecao, papel)
);
create index pessoa_colecao_colecao_idx on pessoa_colecao (colecao, papel);
comment on table pessoa_colecao is 'Atuação de cada pessoa em cada coleção, por papel.';

create table orientacao (
  orientador_id bigint not null references pessoa(id) on delete cascade,
  orientando_id bigint not null references pessoa(id) on delete cascade,
  papel text not null check (papel in ('Orientador', 'Co-orientador')),
  obras int not null,
  primeiro_ano int,
  ultimo_ano int,
  niveis text[] not null,
  colecoes text[] not null,
  primary key (orientador_id, orientando_id, papel)
);
create index orientacao_orientando_idx on orientacao (orientando_id);
comment on table orientacao is 'Pares orientador–autor: quem orientou (ou coorientou) quem, em quantas obras, anos, níveis e coleções.';

create table colecao_perfil (
  colecao text primary key,
  catalogo text not null,
  registros int not null,
  obras int not null,
  registros_com_resumo int not null,
  registros_sem_resumo int not null,
  ano_min int,
  ano_max int,
  autores_distintos int not null,
  orientadores_distintos int not null,
  niveis text[] not null,
  principais_orientadores text[] not null,
  principais_palavras_chave text[] not null,
  principais_macrotemas text[] not null
);
comment on table colecao_perfil is 'Uma linha por coleção (programa de pós ou curso de TCC). catalogo: ppg ou tcc. principais_* em ordem de frequência, até 10.';
comment on column colecao_perfil.principais_orientadores is 'Até 10 orientadores com mais obras orientadas na coleção.';

create table colecao_ano (
  colecao text not null,
  ano int not null,
  registros int not null,
  obras int not null,
  primary key (colecao, ano)
);
comment on table colecao_ano is 'Série anual por coleção. O último ano do acervo está em coleta e não é produção fechada.';

create table termo_perfil (
  termo text primary key,
  obras int not null,
  registros int not null,
  ano_min int,
  ano_max int,
  colecoes int not null,
  pessoas int not null
);
create index termo_perfil_termo_idx on termo_perfil using gin (sem_acento(termo) gin_trgm_ops);
comment on table termo_perfil is 'Uma linha por palavra-chave do acervo: em quantas obras, coleções e pessoas aparece.';

alter table pessoa_fusao enable row level security;
alter table rede_metrica enable row level security;
alter table pessoa_perfil enable row level security;
alter table pessoa_termo enable row level security;
alter table pessoa_macrotema enable row level security;
alter table pessoa_colecao enable row level security;
alter table orientacao enable row level security;
alter table colecao_perfil enable row level security;
alter table colecao_ano enable row level security;
alter table termo_perfil enable row level security;
create policy leitura_publica on pessoa_fusao for select to anon, authenticated using (true);
create policy leitura_publica on rede_metrica for select to anon, authenticated using (true);
create policy leitura_publica on pessoa_perfil for select to anon, authenticated using (true);
create policy leitura_publica on pessoa_termo for select to anon, authenticated using (true);
create policy leitura_publica on pessoa_macrotema for select to anon, authenticated using (true);
create policy leitura_publica on pessoa_colecao for select to anon, authenticated using (true);
create policy leitura_publica on orientacao for select to anon, authenticated using (true);
create policy leitura_publica on colecao_perfil for select to anon, authenticated using (true);
create policy leitura_publica on colecao_ano for select to anon, authenticated using (true);
create policy leitura_publica on termo_perfil for select to anon, authenticated using (true);

-- Refaz todos os agregados a partir das tabelas carregadas. Uma transação: ou
-- os perfis inteiros trocam, ou nada muda. `security definer` pelo mesmo motivo
-- de `atualizar_lexema_frequencia`: quem carrega chama pela API de serviço.
create or replace function atualizar_perfis()
returns table (tabela text, linhas bigint)
language plpgsql security definer
set search_path = public
set statement_timeout = 0
-- Ordenação em memória: no Supabase o espaço de arquivos temporários é pequeno,
-- e com o `work_mem` padrão (3,5 MB) esta função para em "No space left on
-- device" mesmo com o disco do banco quase vazio.
set work_mem = '256MB'
as $$
begin
  truncate pessoa_perfil, pessoa_termo, pessoa_macrotema, pessoa_colecao, orientacao, colecao_perfil, colecao_ano, termo_perfil;

  update rede_metrica m set pessoa_id = p.id
  from pessoa p
  where m.tipo in ('Autor', 'Orientador') and p.nome_canonico = m.rotulo;

  create temporary table vinculo on commit drop as
    select rp.pessoa_id, rp.papel, r.id as registro_id, r.documento_id, r.colecao, r.ano, r.nivel_academico, r.macrotema
    from registro_pessoa rp join registro r on r.id = rp.registro_id;
  create index on vinculo (pessoa_id, papel);
  create index on vinculo (registro_id);
  analyze vinculo;

  insert into pessoa_termo
  select v.pessoa_id, v.papel, pc.termo, count(distinct v.documento_id)
  from vinculo v join registro_palavra_chave pc on pc.registro_id = v.registro_id
  group by 1, 2, 3;

  insert into pessoa_macrotema
  select pessoa_id, papel, macrotema, count(distinct documento_id)
  from vinculo where macrotema is not null group by 1, 2, 3;

  insert into pessoa_colecao
  select pessoa_id, colecao, papel, count(distinct documento_id), count(*), min(ano), max(ano)
  from vinculo group by 1, 2, 3;

  insert into orientacao
  select o.pessoa_id, a.pessoa_id, o.papel, count(distinct o.documento_id), min(o.ano), max(o.ano),
         array_agg(distinct o.nivel_academico) filter (where o.nivel_academico is not null),
         array_agg(distinct o.colecao)
  from vinculo o join vinculo a on a.registro_id = o.registro_id and a.papel = 'Autor'
  where o.papel in ('Orientador', 'Co-orientador') and o.pessoa_id <> a.pessoa_id
  group by 1, 2, 3;

  insert into pessoa_perfil
  select p.id, p.nome_canonico,
    g.grafias,
    count(distinct v.documento_id) filter (where v.papel = 'Autor'),
    count(distinct v.documento_id) filter (where v.papel = 'Orientador'),
    count(distinct v.documento_id) filter (where v.papel = 'Co-orientador'),
    count(*) filter (where v.papel = 'Autor'),
    count(*) filter (where v.papel = 'Orientador'),
    count(*) filter (where v.papel = 'Co-orientador'),
    count(distinct v.documento_id) filter (where v.papel = 'Orientador' and v.nivel_academico = 'Tese (Doutorado)'),
    count(distinct v.documento_id) filter (where v.papel = 'Orientador' and v.nivel_academico = 'Dissertação (Mestrado)'),
    count(distinct v.documento_id) filter (where v.papel = 'Orientador' and v.nivel_academico = 'TCC (Graduação)'),
    count(distinct v.documento_id) filter (where v.papel = 'Orientador' and v.nivel_academico = 'TCC (Especialização)'),
    (select count(distinct o.orientando_id) from orientacao o where o.orientador_id = p.id),
    min(v.ano), max(v.ano),
    min(v.ano) filter (where v.papel <> 'Autor'), max(v.ano) filter (where v.papel <> 'Autor'),
    count(distinct v.colecao),
    (select pc.colecao from pessoa_colecao pc where pc.pessoa_id = p.id group by pc.colecao order by sum(pc.registros) desc, pc.colecao limit 1),
    coalesce((select array_agg(t.termo order by t.obras desc, t.termo) from (select termo, obras from pessoa_termo t where t.pessoa_id = p.id and t.papel = 'Autor' order by obras desc, termo limit 10) t), '{}'),
    coalesce((select array_agg(t.termo order by t.obras desc, t.termo) from (select termo, sum(obras) as obras from pessoa_termo t where t.pessoa_id = p.id and t.papel <> 'Autor' group by termo order by 2 desc, termo limit 10) t), '{}'),
    coalesce((select array_agg(m.macrotema order by m.obras desc, m.macrotema) from (select macrotema, obras from pessoa_macrotema m where m.pessoa_id = p.id and m.papel = 'Autor' order by obras desc, macrotema limit 5) m), '{}'),
    coalesce((select array_agg(m.macrotema order by m.obras desc, m.macrotema) from (select macrotema, sum(obras) as obras from pessoa_macrotema m where m.pessoa_id = p.id and m.papel <> 'Autor' group by macrotema order by 2 desc, macrotema limit 5) m), '{}'),
    (select rm.intermediacao from rede_metrica rm where rm.pessoa_id = p.id and rm.escopo = 'acervo' limit 1),
    (select rm.ranking from rede_metrica rm where rm.pessoa_id = p.id and rm.escopo = 'acervo' limit 1)
  from pessoa p join vinculo v on v.pessoa_id = p.id
  join (select pessoa_id, count(*)::int as grafias from pessoa_grafia group by pessoa_id) g on g.pessoa_id = p.id
  group by p.id, p.nome_canonico, g.grafias;

  update pessoa_perfil set nome_tokens = tokens_de_nome(nome);

  update rede_metrica m set ranking_entre_pessoas = x.posicao
  from (
    select ctid, rank() over (partition by escopo, colecao order by intermediacao desc nulls last) as posicao
    from rede_metrica where tipo in ('Autor', 'Orientador')
  ) x
  where m.ctid = x.ctid;

  insert into colecao_ano
  select colecao, ano, count(*), count(distinct documento_id) from registro where ano is not null group by 1, 2;

  insert into colecao_perfil
  select r.colecao, min(r.catalogo), count(*), count(distinct r.documento_id),
    count(*) filter (where r.resumo_utilizavel), count(*) filter (where not r.resumo_utilizavel),
    min(r.ano), max(r.ano),
    (select count(distinct pc.pessoa_id) from pessoa_colecao pc where pc.colecao = r.colecao and pc.papel = 'Autor'),
    (select count(distinct pc.pessoa_id) from pessoa_colecao pc where pc.colecao = r.colecao and pc.papel = 'Orientador'),
    array_agg(distinct r.nivel_academico) filter (where r.nivel_academico is not null),
    coalesce((select array_agg(p.nome_canonico order by pc.obras desc, p.nome_canonico) from (select pessoa_id, obras from pessoa_colecao pc where pc.colecao = r.colecao and pc.papel = 'Orientador' order by obras desc limit 10) pc join pessoa p on p.id = pc.pessoa_id), '{}'),
    coalesce((select array_agg(t.termo order by t.n desc, t.termo) from (select pc.termo, count(distinct r2.documento_id) as n from registro r2 join registro_palavra_chave pc on pc.registro_id = r2.id where r2.colecao = r.colecao group by pc.termo order by 2 desc, pc.termo limit 10) t), '{}'),
    coalesce((select array_agg(t.macrotema order by t.n desc, t.macrotema) from (select r2.macrotema, count(distinct r2.documento_id) as n from registro r2 where r2.colecao = r.colecao and r2.macrotema is not null group by r2.macrotema order by 2 desc, r2.macrotema limit 10) t), '{}')
  from registro r group by r.colecao;

  insert into termo_perfil
  select pc.termo, count(distinct r.documento_id), count(*), min(r.ano), max(r.ano), count(distinct r.colecao),
         coalesce(max(t.pessoas), 0)
  from registro_palavra_chave pc join registro r on r.id = pc.registro_id
  left join (select termo, count(distinct pessoa_id)::int as pessoas from pessoa_termo group by termo) t on t.termo = pc.termo
  group by pc.termo;

  analyze pessoa_perfil, pessoa_termo, pessoa_macrotema, pessoa_colecao, orientacao, colecao_perfil, colecao_ano, termo_perfil, rede_metrica;

  return query values
    ('pessoa_perfil', (select count(*) from pessoa_perfil)),
    ('pessoa_termo', (select count(*) from pessoa_termo)),
    ('pessoa_macrotema', (select count(*) from pessoa_macrotema)),
    ('pessoa_colecao', (select count(*) from pessoa_colecao)),
    ('orientacao', (select count(*) from orientacao)),
    ('colecao_perfil', (select count(*) from colecao_perfil)),
    ('colecao_ano', (select count(*) from colecao_ano)),
    ('termo_perfil', (select count(*) from termo_perfil)),
    ('rede_metrica com pessoa', (select count(*) from rede_metrica where pessoa_id is not null));
end;
$$;

revoke execute on function atualizar_perfis() from public, anon, authenticated;
grant execute on function atualizar_perfis() to service_role;

comment on column rede_metrica.ranking_entre_pessoas is 'Posição por intermediação decrescente só entre pessoas (autores e orientadores) do mesmo escopo e coleção (1 = pessoa que mais faz ponte).';
comment on column pessoa_perfil.nome_tokens is 'Tokens do nome sem acento e sem partículas, em ordem alfabética. Para achar alguém em qualquer ordem: nome_tokens @> tokens_de_nome(''patricia de sa freire'').';

-- ============================================================================
-- Camada de consulta para NL2SQL (ADR 004, fase A0).
--
-- O modelo nunca lê as tabelas: lê as views do schema `consulta`, cada coluna
-- com a unidade no nome e descrição em `consulta.dicionario`. E nunca executa
-- SQL com o privilégio do app: `consultar()` repassa para `consulta.executar`,
-- que roda como `consulta_leitor`, um papel com SELECT só nessas views. A função
-- é STABLE, e o Postgres recusa escrita e DDL dentro dela — a trava de escrita
-- não depende de a validação de texto estar certa.
-- ============================================================================

create schema if not exists consulta;
comment on schema consulta is 'Views para consulta em linguagem natural (NL2SQL). Somente leitura. obras_* conta trabalhos distintos; registros_* conta catalogações.';

create or replace view consulta.acervo as
  select m.base_version, m.gerado_em,
    (select count(*) from registro) as registros,
    (select count(*) from documento) as obras,
    (select count(*) from registro where resumo_utilizavel) as registros_com_resumo,
    (select count(*) from registro where not resumo_utilizavel) as registros_sem_resumo,
    (select count(distinct colecao) from registro) as colecoes,
    (select count(*) from pessoa) as pessoas,
    (select max(ano) from registro) as ano_em_coleta
  from indice_meta m;

create or replace view consulta.pessoas as select * from pessoa_perfil;
create or replace view consulta.pessoa_grafias as
  select g.grafia, g.pessoa_id, p.nome_canonico as nome, f.metodo as metodo_fusao, f.decisao as decisao_curadoria
  from pessoa_grafia g join pessoa p on p.id = g.pessoa_id left join pessoa_fusao f on f.grafia = g.grafia;
create or replace view consulta.pessoa_palavras_chave as
  select t.pessoa_id, p.nome_canonico as nome, t.papel, t.termo, t.obras from pessoa_termo t join pessoa p on p.id = t.pessoa_id;
create or replace view consulta.pessoa_macrotemas as
  select m.pessoa_id, p.nome_canonico as nome, m.papel, m.macrotema, m.obras from pessoa_macrotema m join pessoa p on p.id = m.pessoa_id;
create or replace view consulta.pessoa_colecoes as
  select c.pessoa_id, p.nome_canonico as nome, c.colecao, c.papel, c.obras, c.registros, c.primeiro_ano, c.ultimo_ano
  from pessoa_colecao c join pessoa p on p.id = c.pessoa_id;
create or replace view consulta.orientacoes as
  select o.orientador_id, po.nome_canonico as orientador, o.orientando_id, pa.nome_canonico as orientando,
         o.papel, o.obras, o.primeiro_ano, o.ultimo_ano, o.niveis, o.colecoes
  from orientacao o join pessoa po on po.id = o.orientador_id join pessoa pa on pa.id = o.orientando_id;
create or replace view consulta.colecoes as select * from colecao_perfil;
create or replace view consulta.colecoes_por_ano as select * from colecao_ano;
create or replace view consulta.palavras_chave as select * from termo_perfil;
create or replace view consulta.macrotemas as
  select macrotema, count(*) as registros, count(distinct documento_id) as obras, count(distinct colecao) as colecoes,
         min(ano) as ano_min, max(ano) as ano_max
  from registro where macrotema is not null group by macrotema;
create or replace view consulta.rede as
  select escopo, colecao, tipo, rotulo, pessoa_id, grau_absoluto, grau, intermediacao, proximidade, agrupamento,
         comunidade, ranking, ranking_entre_pessoas, nos_na_rede
  from rede_metrica;
create or replace view consulta.obras as
  select id as documento_id, titulo, resumo_utilizavel from documento;
create or replace view consulta.registros as
  select r.id as registro_id, r.documento_id, d.titulo, r.colecao, r.catalogo, r.ano, r.nivel_academico, r.macrotema, r.url, r.resumo_utilizavel
  from registro r join documento d on d.id = r.documento_id;
create or replace view consulta.registro_pessoas as
  select rp.registro_id, r.documento_id, rp.pessoa_id, p.nome_canonico as nome, rp.papel, r.colecao, r.ano, r.nivel_academico
  from registro_pessoa rp join registro r on r.id = rp.registro_id join pessoa p on p.id = rp.pessoa_id;
create or replace view consulta.registro_palavras_chave as
  select pc.registro_id, r.documento_id, pc.termo, r.colecao, r.ano
  from registro_palavra_chave pc join registro r on r.id = pc.registro_id;

comment on view consulta.acervo is 'Uma linha: tamanho do acervo e versão do índice. ano_em_coleta é o último ano, que ainda não é produção fechada.';
comment on view consulta.pessoas is 'Uma linha por pessoa unificada (unificação automática conservadora, sem curadoria humana). Para achar pelo nome em qualquer ordem: where nome_tokens @> tokens_de_nome(''nome buscado'').';
comment on view consulta.pessoa_grafias is 'Cada grafia do acervo e a pessoa em que foi unificada. metodo_fusao nulo: é a grafia canônica ou não foi fundida.';
comment on view consulta.pessoa_palavras_chave is 'Palavras-chave das obras de cada pessoa por papel (Autor, Orientador, Co-orientador); obras = trabalhos distintos com o termo.';
comment on view consulta.pessoa_macrotemas is 'Macrotemas das obras de cada pessoa por papel. Macrotema é classificação automática (NMF) da base, não categoria oficial.';
comment on view consulta.pessoa_colecoes is 'Atuação de cada pessoa em cada coleção, por papel.';
comment on view consulta.orientacoes is 'Quem orientou (papel Orientador) ou coorientou (Co-orientador) quem, com obras, anos, níveis e coleções.';
comment on view consulta.colecoes is 'Uma linha por coleção: programa de pós-graduação (catalogo=ppg) ou curso de TCC (catalogo=tcc).';
comment on view consulta.colecoes_por_ano is 'Série anual por coleção.';
comment on view consulta.palavras_chave is 'Uma linha por palavra-chave (termo, minúsculo e sem acento), com obras, registros, anos, coleções e pessoas.';
comment on view consulta.macrotemas is 'Uma linha por macrotema (classificação automática NMF da base, não categoria oficial do programa).';
comment on view consulta.rede is 'Métricas da rede documento–pessoa–palavra-chave–macrotema, por escopo (acervo ou colecao). tipo: Autor, Orientador, Palavra-chave, Macrotema. Compare só dentro do mesmo escopo e coleção.';
comment on view consulta.obras is 'Uma linha por obra deduplicada (trabalho distinto). Sem o texto do resumo.';
comment on view consulta.registros is 'Uma linha por catalogação: a mesma obra pode ter vários registros em coleções diferentes. nivel_academico: TCC (Graduação), Dissertação (Mestrado), Tese (Doutorado), TCC (Especialização), Outros.';
comment on view consulta.registro_pessoas is 'Vínculo registro–pessoa com papel (Autor, Orientador, Co-orientador), coleção, ano e nível. Contar obras: count(distinct documento_id).';
comment on view consulta.registro_palavras_chave is 'Palavras-chave de cada registro, com coleção e ano.';

-- Os comentários das colunas vêm das tabelas de origem, casados por nome.
do $$
declare v record; c record; descricao text;
begin
  for v in select * from (values
    ('pessoas', 'pessoa_perfil'), ('colecoes', 'colecao_perfil'), ('colecoes_por_ano', 'colecao_ano'),
    ('palavras_chave', 'termo_perfil'), ('rede', 'rede_metrica'), ('orientacoes', 'orientacao'),
    ('pessoa_colecoes', 'pessoa_colecao'), ('pessoa_palavras_chave', 'pessoa_termo'), ('pessoa_macrotemas', 'pessoa_macrotema')
  ) as t(visao, tabela) loop
    for c in select a.attname from pg_attribute a
             where a.attrelid = ('consulta.' || v.visao)::regclass and a.attnum > 0 and not a.attisdropped loop
      descricao := col_description(('public.' || v.tabela)::regclass,
        (select attnum from pg_attribute where attrelid = ('public.' || v.tabela)::regclass and attname = c.attname));
      if descricao is not null then
        execute format('comment on column consulta.%I.%I is %L', v.visao, c.attname, descricao);
      end if;
    end loop;
  end loop;
end $$;

-- Glossário por nome de coluna, para o que a origem não descreve. Um nome, um
-- significado, em todas as views: é o que impede `obras` de querer dizer
-- registros numa view e trabalhos distintos em outra.
do $$
declare g record; c record;
begin
  for g in select * from (values
    ('pessoa_id', 'Identificador da pessoa unificada; junta com pessoas.pessoa_id.'),
    ('nome', 'Nome canônico da pessoa no formato "Sobrenome, Prenomes". Para buscar em qualquer ordem use pessoas.nome_tokens @> tokens_de_nome(''...'').'),
    ('orientador', 'Nome canônico de quem orientou ou coorientou ("Sobrenome, Prenomes").'),
    ('orientando', 'Nome canônico do autor orientado ("Sobrenome, Prenomes").'),
    ('orientador_id', 'pessoa_id de quem orientou ou coorientou.'),
    ('orientando_id', 'pessoa_id do autor orientado.'),
    ('papel', 'Autor, Orientador ou Co-orientador.'),
    ('obras', 'Trabalhos distintos (obra deduplicada). Não confundir com registros.'),
    ('registros', 'Catalogações: a mesma obra em duas coleções conta 2.'),
    ('obras_como_autor', 'Trabalhos distintos em que a pessoa é autora.'),
    ('obras_orientadas', 'Trabalhos distintos que a pessoa orientou, em qualquer nível.'),
    ('obras_coorientadas', 'Trabalhos distintos que a pessoa coorientou.'),
    ('registros_como_autor', 'Catalogações em que a pessoa é autora.'),
    ('registros_orientados', 'Catalogações que a pessoa orientou.'),
    ('registros_coorientados', 'Catalogações que a pessoa coorientou.'),
    ('orientadas_doutorado', 'Teses de doutorado orientadas (obras distintas).'),
    ('orientadas_mestrado', 'Dissertações de mestrado orientadas (obras distintas).'),
    ('orientadas_tcc_especializacao', 'TCCs de especialização orientados (obras distintas).'),
    ('ultimo_ano', 'Último ano com qualquer papel no recorte da linha.'),
    ('primeiro_ano', 'Primeiro ano no recorte da linha.'),
    ('ultimo_ano_orientando', 'Último ano como orientador ou coorientador.'),
    ('macrotemas_como_orientador', 'Até 5 macrotemas das obras orientadas ou coorientadas; classificação automática, não oficial.'),
    ('colecoes', 'Quantidade de coleções distintas (ou, em orientacoes, a lista delas).'),
    ('colecao', 'Nome da coleção: programa de pós-graduação ou curso de TCC.'),
    ('catalogo', 'ppg (pós-graduação) ou tcc (trabalho de conclusão de curso).'),
    ('niveis', 'Níveis acadêmicos presentes: TCC (Graduação), Dissertação (Mestrado), Tese (Doutorado), TCC (Especialização), Outros.'),
    ('nivel_academico', 'TCC (Graduação), Dissertação (Mestrado), Tese (Doutorado), TCC (Especialização) ou Outros.'),
    ('ano', 'Ano do registro. O último ano do acervo está em coleta.'),
    ('ano_min', 'Primeiro ano.'),
    ('ano_max', 'Último ano; o último ano do acervo está em coleta.'),
    ('registros_com_resumo', 'Catalogações com resumo utilizável (200 caracteres ou mais).'),
    ('registros_sem_resumo', 'Catalogações sem resumo utilizável.'),
    ('resumo_utilizavel', 'Verdadeiro quando há resumo com 200 caracteres ou mais.'),
    ('autores_distintos', 'Pessoas distintas com papel de autor na coleção.'),
    ('orientadores_distintos', 'Pessoas distintas com papel de orientador na coleção.'),
    ('principais_palavras_chave', 'Até 10 palavras-chave mais frequentes (por obras distintas).'),
    ('principais_macrotemas', 'Até 10 macrotemas mais frequentes; classificação automática, não oficial.'),
    ('termo', 'Palavra-chave, em minúsculas e sem acento, como catalogada.'),
    ('pessoas', 'Pessoas distintas (em qualquer papel) ligadas ao termo; em acervo, total de pessoas unificadas.'),
    ('macrotema', 'Macrotema: classificação automática (NMF) da base, não categoria oficial do programa.'),
    ('documento_id', 'Identificador da obra deduplicada; count(distinct documento_id) conta trabalhos.'),
    ('registro_id', 'Identificador da catalogação.'),
    ('titulo', 'Título da obra.'),
    ('url', 'Endereço da obra no repositório institucional da UFSC.'),
    ('grafia', 'Como o nome aparece escrito no acervo.'),
    ('metodo_fusao', 'normalizacao ou abreviacao, quando a grafia foi fundida automaticamente; nulo quando não foi.'),
    ('decisao_curadoria', 'confirmada ou desfeita pela curadoria humana; nulo enquanto não revisada.'),
    ('escopo', 'acervo (rede do acervo inteiro) ou colecao (rede de uma coleção sozinha).'),
    ('tipo', 'Tipo do nó: Autor, Orientador, Palavra-chave, Macrotema ou Artefato (Ontologia IA).'),
    ('rotulo', 'Nome do nó na rede: pessoa (canônica), palavra-chave ou macrotema.'),
    ('grau_absoluto', 'Número de conexões diretas do nó (obras ligadas).'),
    ('nos_na_rede', 'Total de nós da rede do escopo, inclusive documentos.'),
    ('base_version', 'Versão das bases que geraram o índice.'),
    ('gerado_em', 'Quando o índice foi gerado.'),
    ('ano_em_coleta', 'Último ano do acervo, ainda em coleta: não tratar como ano fechado.')
  ) as t(coluna, descricao) loop
    for c in select cl.relname from pg_attribute a join pg_class cl on cl.oid = a.attrelid join pg_namespace n on n.oid = cl.relnamespace
             where n.nspname = 'consulta' and cl.relkind = 'v' and a.attname = g.coluna and a.attnum > 0
               and col_description(cl.oid, a.attnum) is null loop
      execute format('comment on column consulta.%I.%I is %L', c.relname, g.coluna, g.descricao);
    end loop;
  end loop;
end $$;

create or replace view consulta.dicionario as
  select c.relname as visao, obj_description(c.oid, 'pg_class') as descricao_visao,
         a.attname as coluna, format_type(a.atttypid, a.atttypmod) as tipo, col_description(c.oid, a.attnum) as descricao
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
  where n.nspname = 'consulta' and c.relkind = 'v' and c.relname <> 'dicionario'
  order by c.relname, a.attnum;
comment on view consulta.dicionario is 'O esquema consultável: views, colunas, tipos e descrições. É o que o modelo lê antes de escrever SQL.';

do $$ begin
  if not exists (select 1 from pg_roles where rolname = 'consulta_leitor') then create role consulta_leitor nologin; end if;
end $$;
grant usage on schema consulta to consulta_leitor;
grant select on all tables in schema consulta to consulta_leitor;
grant execute on function tokens_de_nome(text), sem_acento(text) to consulta_leitor;

-- Executa uma consulta do modelo: um único SELECT (ou WITH … SELECT), no máximo
-- `limite` linhas em JSON, na ordem das colunas, dizendo se truncou.
create or replace function consulta.executar(consulta_sql text, limite int)
returns json
language plpgsql stable security definer
set search_path = consulta, public, pg_catalog
set statement_timeout = '3s'
as $$
declare
  texto text := regexp_replace(btrim(coalesce(consulta_sql, '')), ';\s*$', '');
  teto int := least(greatest(coalesce(limite, 200), 1), 1000);
  linhas json;
  total int;
begin
  if length(texto) > 4000 then raise exception 'consulta longa demais (máximo de 4.000 caracteres)'; end if;
  if texto !~* '^\s*(select|with)\s' then raise exception 'só é aceito SELECT'; end if;
  if position(';' in texto) > 0 then raise exception 'uma consulta por vez, sem ";"'; end if;
  execute format('select json_agg(q) from (select * from (%s) as consulta_modelo limit %s) q', texto, teto + 1) into linhas;
  total := coalesce(json_array_length(linhas), 0);
  if total > teto then
    select json_agg(e order by i) into linhas from json_array_elements(linhas) with ordinality as x(e, i) where i <= teto;
  end if;
  return json_build_object('linhas', coalesce(linhas, '[]'::json), 'truncado', total > teto, 'limite', teto);
end;
$$;

-- Dono `consulta_leitor`: a execução roda com o privilégio dele, não do app.
-- O CREATE no schema só existe durante a troca de dono.
-- No Postgres 17, criar o papel não basta para passar objetos a ele: é preciso
-- poder assumi-lo (SET), e o contrário não vale — `consulta_leitor` não assume
-- `postgres`.
grant consulta_leitor to current_user with set true;
grant create on schema consulta to consulta_leitor;
alter function consulta.executar(text, int) owner to consulta_leitor;
revoke create on schema consulta from consulta_leitor;
revoke execute on function consulta.executar(text, int) from public;

-- Porta de entrada pela API: o PostgREST expõe só `public`.
create or replace function consultar(consulta_sql text, limite int default 200)
returns json
language sql stable
set search_path = public
as $$ select consulta.executar(consulta_sql, limite) $$;

grant usage on schema consulta to anon, authenticated;
grant execute on function consulta.executar(text, int) to anon, authenticated;
grant execute on function consultar(text, int) to anon, authenticated;
